//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModioX.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModioX.Languages.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Console Profile.
        /// </summary>
        internal static string Add_New_Console_Profile {
            get {
                return ResourceManager.GetString("Add New Console Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Your Games.
        /// </summary>
        internal static string Add_Your_Games {
            get {
                return ResourceManager.GetString("Add Your Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANNOUNCEMENTS.
        /// </summary>
        internal static string ANNOUNCEMENTS {
            get {
                return ResourceManager.GetString("ANNOUNCEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE LOG.
        /// </summary>
        internal static string CHANGE_LOG {
            get {
                return ResourceManager.GetString("CHANGE LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Add New Console&apos; to create a profile.
        /// </summary>
        internal static string Click__Add_New_Console__to_create_a_profile {
            get {
                return ResourceManager.GetString("Click \'Add New Console\' to create a profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECT.
        /// </summary>
        internal static string CONNECT {
            get {
                return ResourceManager.GetString("CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to console.
        /// </summary>
        internal static string Connect_to_console {
            get {
                return ResourceManager.GetString("Connect to console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to.
        /// </summary>
        internal static string Connecting_to {
            get {
                return ResourceManager.GetString("Connecting to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        internal static string Connection_Failed {
            get {
                return ResourceManager.GetString("Connection Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRIBUTORS.
        /// </summary>
        internal static string CONTRIBUTORS {
            get {
                return ResourceManager.GetString("CONTRIBUTORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDITS.
        /// </summary>
        internal static string CREDITS {
            get {
                return ResourceManager.GetString("CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DASHBOARD.
        /// </summary>
        internal static string DASHBOARD {
            get {
                return ResourceManager.GetString("DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Game Regions.
        /// </summary>
        internal static string Default_Game_Regions {
            get {
                return ResourceManager.GetString("Default Game Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Find Directory.
        /// </summary>
        internal static string Directory_can_t_find {
            get {
                return ResourceManager.GetString("Directory can\'t find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This directory doesn&apos;t exist on your computer.
        /// </summary>
        internal static string Directory_does_not_exist {
            get {
                return ResourceManager.GetString("Directory does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from console.
        /// </summary>
        internal static string Disconnect_from_console {
            get {
                return ResourceManager.GetString("Disconnect from console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting from console.
        /// </summary>
        internal static string Disconnecting_from_console {
            get {
                return ResourceManager.GetString("Disconnecting from console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        internal static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string Downloading___ {
            get {
                return ResourceManager.GetString("Downloading...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOADS.
        /// </summary>
        internal static string DOWNLOADS {
            get {
                return ResourceManager.GetString("DOWNLOADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads Location.
        /// </summary>
        internal static string Downloads_Location {
            get {
                return ResourceManager.GetString("Downloads Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Console Profiles.
        /// </summary>
        internal static string Edit_Console_Profiles {
            get {
                return ResourceManager.GetString("Edit Console Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching drives.
        /// </summary>
        internal static string Fetching_drives {
            get {
                return ResourceManager.GetString("Fetching drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching root directories.
        /// </summary>
        internal static string Fetching_root_directories {
            get {
                return ResourceManager.GetString("Fetching root directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE MANAGER.
        /// </summary>
        internal static string FILE_MANAGER {
            get {
                return ResourceManager.GetString("FILE MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME MODS.
        /// </summary>
        internal static string GAME_MODS {
            get {
                return ResourceManager.GetString("GAME MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME SAVES.
        /// </summary>
        internal static string GAME_SAVES {
            get {
                return ResourceManager.GetString("GAME SAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Saves Total.
        /// </summary>
        internal static string Game_Saves_Total {
            get {
                return ResourceManager.GetString("Game Saves Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAMES.
        /// </summary>
        internal static string GAMES {
            get {
                return ResourceManager.GetString("GAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Favorites.
        /// </summary>
        internal static string Hide_Favorites {
            get {
                return ResourceManager.GetString("Hide Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOMEBREW.
        /// </summary>
        internal static string HOMEBREW {
            get {
                return ResourceManager.GetString("HOMEBREW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized.
        /// </summary>
        internal static string Initialized {
            get {
                return ResourceManager.GetString("Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing the application database....
        /// </summary>
        internal static string Initializing_the_application_database___ {
            get {
                return ResourceManager.GetString("Initializing the application database...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install File.
        /// </summary>
        internal static string Install_File {
            get {
                return ResourceManager.GetString("Install File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Files.
        /// </summary>
        internal static string Install_Files {
            get {
                return ResourceManager.GetString("Install Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALLED MODS.
        /// </summary>
        internal static string INSTALLED_MODS {
            get {
                return ResourceManager.GetString("INSTALLED MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        internal static string Installing___ {
            get {
                return ResourceManager.GetString("Installing...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Introduction Details.
        /// </summary>
        internal static string Introduction_Details {
            get {
                return ResourceManager.GetString("Introduction Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Not Supported.
        /// </summary>
        internal static string Language_Not_Supported {
            get {
                return ResourceManager.GetString("Language Not Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but this language is currently not supported yet. If you would like to help us add this language, please join our Discord Server and let us know!.
        /// </summary>
        internal static string Language_not_supported__can_help {
            get {
                return ResourceManager.GetString("Language not supported, can help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        internal static string Last_Updated {
            get {
                return ResourceManager.GetString("Last Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LATEST NEWS.
        /// </summary>
        internal static string LATEST_NEWS {
            get {
                return ResourceManager.GetString("LATEST NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LET&apos;S GET YOU SETUP.
        /// </summary>
        internal static string LET_S_GET_YOU_SETUP {
            get {
                return ResourceManager.GetString("LET\'S GET YOU SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure Neighborhood is installed on your computer.
        /// </summary>
        internal static string Make_sure_Neighborhood_is_installed_on_your_computer {
            get {
                return ResourceManager.GetString("Make sure Neighborhood is installed on your computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODS.
        /// </summary>
        internal static string MODS {
            get {
                return ResourceManager.GetString("MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods Total.
        /// </summary>
        internal static string Mods_Total {
            get {
                return ResourceManager.GetString("Mods Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO ANNOUNCEMENTS.
        /// </summary>
        internal static string NO_ANNOUNCEMENTS {
            get {
                return ResourceManager.GetString("NO ANNOUNCEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Console Connected.
        /// </summary>
        internal static string No_Console_Connected {
            get {
                return ResourceManager.GetString("No Console Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO CONSOLE PROFILES.
        /// </summary>
        internal static string NO_CONSOLE_PROFILES {
            get {
                return ResourceManager.GetString("NO CONSOLE PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection detected..
        /// </summary>
        internal static string No_Internet_connection_detected {
            get {
                return ResourceManager.GetString("No Internet connection detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Detected.
        /// </summary>
        internal static string No_Internet_Detected {
            get {
                return ResourceManager.GetString("No Internet Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No news is good news!.
        /// </summary>
        internal static string No_news_is_good_news_ {
            get {
                return ResourceManager.GetString("No news is good news!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        internal static string Not_Connected {
            get {
                return ResourceManager.GetString("Not Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Installed.
        /// </summary>
        internal static string Not_Installed {
            get {
                return ResourceManager.GetString("Not Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONS.
        /// </summary>
        internal static string OPTIONS {
            get {
                return ResourceManager.GetString("OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACKAGES.
        /// </summary>
        internal static string PACKAGES {
            get {
                return ResourceManager.GetString("PACKAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages Total.
        /// </summary>
        internal static string Packages_Total {
            get {
                return ResourceManager.GetString("Packages Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLUGINS.
        /// </summary>
        internal static string PLUGINS {
            get {
                return ResourceManager.GetString("PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins Total.
        /// </summary>
        internal static string Plugins_Total {
            get {
                return ResourceManager.GetString("Plugins Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to connect to console.
        /// </summary>
        internal static string Ready_to_connect_to_console {
            get {
                return ResourceManager.GetString("Ready to connect to console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESOURCES.
        /// </summary>
        internal static string RESOURCES {
            get {
                return ResourceManager.GetString("RESOURCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required.
        /// </summary>
        internal static string Restart_Required {
            get {
                return ResourceManager.GetString("Restart Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan For Xbox Consoles.
        /// </summary>
        internal static string Scan_For_Xbox_Consoles {
            get {
                return ResourceManager.GetString("Scan For Xbox Consoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Downloads Location.
        /// </summary>
        internal static string Set_Downloads_Location {
            get {
                return ResourceManager.GetString("Set Downloads Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Favorites.
        /// </summary>
        internal static string Show_Favorites {
            get {
                return ResourceManager.GetString("Show Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIAL THANKS.
        /// </summary>
        internal static string SPECIAL_THANKS {
            get {
                return ResourceManager.GetString("SPECIAL THANKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Library.
        /// </summary>
        internal static string Startup_Library {
            get {
                return ResourceManager.GetString("Startup Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATISTICS.
        /// </summary>
        internal static string STATISTICS {
            get {
                return ResourceManager.GetString("STATISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected to console.
        /// </summary>
        internal static string Successfully_connected_to_console {
            get {
                return ResourceManager.GetString("Successfully connected to console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully disconnected from console.
        /// </summary>
        internal static string Successfully_disconnected_from_console {
            get {
                return ResourceManager.GetString("Successfully disconnected from console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully fetched root directories.
        /// </summary>
        internal static string Successfully_fetched_root_directories {
            get {
                return ResourceManager.GetString("Successfully fetched root directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully loaded the database - Finalizing application data....
        /// </summary>
        internal static string Successfully_loaded_the_database___Finalizing_application_data___ {
            get {
                return ResourceManager.GetString("Successfully loaded the database - Finalizing application data...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOOLS.
        /// </summary>
        internal static string TOOLS {
            get {
                return ResourceManager.GetString("TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to.
        /// </summary>
        internal static string Unable_to_connect_to {
            get {
                return ResourceManager.GetString("Unable to connect to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfavorite.
        /// </summary>
        internal static string Unfavorite {
            get {
                return ResourceManager.GetString("Unfavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall File.
        /// </summary>
        internal static string Uninstall_File {
            get {
                return ResourceManager.GetString("Uninstall File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Files.
        /// </summary>
        internal static string Uninstall_Files {
            get {
                return ResourceManager.GetString("Uninstall Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled.
        /// </summary>
        internal static string Uninstalled {
            get {
                return ResourceManager.GetString("Uninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        internal static string Uninstalling___ {
            get {
                return ResourceManager.GetString("Uninstalling...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now connected to.
        /// </summary>
        internal static string You_are_now_connected_to {
            get {
                return ResourceManager.GetString("You are now connected to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have No Lists.
        /// </summary>
        internal static string You_Have_No_Lists {
            get {
                return ResourceManager.GetString("You Have No Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be connected to the Internet to use this application..
        /// </summary>
        internal static string You_must_be_connected_to_the_Internet_to_use_this_application_ {
            get {
                return ResourceManager.GetString("You must be connected to the Internet to use this application.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be connected to your console to use this feature..
        /// </summary>
        internal static string You_must_be_connected_to_your_console_to_use_this_feature_ {
            get {
                return ResourceManager.GetString("You must be connected to your console to use this feature.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart the application for this change to take effect. Would you like to restart now?.
        /// </summary>
        internal static string You_must_restart_the_application_for_this_change_to_take_effect__Would_you_like_to_restart_now_ {
            get {
                return ResourceManager.GetString("You must restart the application for this change to take effect. Would you like t" +
                        "o restart now?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Lists.
        /// </summary>
        internal static string Your_Lists {
            get {
                return ResourceManager.GetString("Your Lists", resourceCulture);
            }
        }
    }
}
