//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModioX.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModioX.Languages.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANNOUNCEMENTS.
        /// </summary>
        internal static string ANNOUNCEMENTS {
            get {
                return ResourceManager.GetString("ANNOUNCEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup/Restore Game Files.
        /// </summary>
        internal static string BACKUP_FILES {
            get {
                return ResourceManager.GetString("BACKUP_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE LOG.
        /// </summary>
        internal static string CHANGE_LOG {
            get {
                return ResourceManager.GetString("CHANGE_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete all of your downloads?.
        /// </summary>
        internal static string CONFIRM_DELETE_ALL_DOWNLOADS {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE_ALL_DOWNLOADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete All.
        /// </summary>
        internal static string CONFIRM_DELETE_ALL_TITLE {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE_ALL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the selected item?.
        /// </summary>
        internal static string CONFIRM_DELETE_ITEM {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the selected item from your downloads?.
        /// </summary>
        internal static string CONFIRM_DELETE_ITEM_DOWNLOADS {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE_ITEM_DOWNLOADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECT.
        /// </summary>
        internal static string CONNECT {
            get {
                return ResourceManager.GetString("CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to console.
        /// </summary>
        internal static string CONNECT_TO_CONSOLE {
            get {
                return ResourceManager.GetString("CONNECT_TO_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to.
        /// </summary>
        internal static string CONNECTING_TO {
            get {
                return ResourceManager.GetString("CONNECTING_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        internal static string CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console Manager.
        /// </summary>
        internal static string CONSOLE_MANAGER {
            get {
                return ResourceManager.GetString("CONSOLE_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Console Profile.
        /// </summary>
        internal static string CONSOLE_PROFILE_ADD {
            get {
                return ResourceManager.GetString("CONSOLE_PROFILE_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Add New Console&apos; to create a profile.
        /// </summary>
        internal static string CONSOLE_PROFILE_ADD_INSTRUCTION {
            get {
                return ResourceManager.GetString("CONSOLE_PROFILE_ADD_INSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Console Profiles.
        /// </summary>
        internal static string CONSOLE_PROFILES_EDIT {
            get {
                return ResourceManager.GetString("CONSOLE_PROFILES_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRIBUTORS.
        /// </summary>
        internal static string CONTRIBUTORS {
            get {
                return ResourceManager.GetString("CONTRIBUTORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDITS.
        /// </summary>
        internal static string CREDITS {
            get {
                return ResourceManager.GetString("CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DASHBOARD.
        /// </summary>
        internal static string DASHBOARD {
            get {
                return ResourceManager.GetString("DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Game Regions.
        /// </summary>
        internal static string DEFAULT_GAME_REGIONS {
            get {
                return ResourceManager.GetString("DEFAULT_GAME_REGIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Items.
        /// </summary>
        internal static string DELETE_ALL_ITEMS {
            get {
                return ResourceManager.GetString("DELETE_ALL_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item.
        /// </summary>
        internal static string DELETE_ITEM {
            get {
                return ResourceManager.GetString("DELETE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete item. Error: {0}.
        /// </summary>
        internal static string DELETE_ITEM_ERROR {
            get {
                return ResourceManager.GetString("DELETE_ITEM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Directory.
        /// </summary>
        internal static string DIRECTORY_EMPTY {
            get {
                return ResourceManager.GetString("DIRECTORY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This directory doesn&apos;t exist on your computer..
        /// </summary>
        internal static string DIRECTORY_NOT_EXIST {
            get {
                return ResourceManager.GetString("DIRECTORY_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Not Found.
        /// </summary>
        internal static string DIRECTORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("DIRECTORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from console.
        /// </summary>
        internal static string DISCONNECT_FROM_CONSOLE {
            get {
                return ResourceManager.GetString("DISCONNECT_FROM_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string DISCONNECT_LOWERCASE {
            get {
                return ResourceManager.GetString("DISCONNECT_LOWERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting from console.
        /// </summary>
        internal static string DISCONNECTING_FROM_CONSOLE {
            get {
                return ResourceManager.GetString("DISCONNECTING_FROM_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        internal static string DOWNLOADED {
            get {
                return ResourceManager.GetString("DOWNLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string DOWNLOADING {
            get {
                return ResourceManager.GetString("DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOADS.
        /// </summary>
        internal static string DOWNLOADS {
            get {
                return ResourceManager.GetString("DOWNLOADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads Location.
        /// </summary>
        internal static string DOWNLOADS_LOCATION {
            get {
                return ResourceManager.GetString("DOWNLOADS_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string FAVORITES_ADD {
            get {
                return ResourceManager.GetString("FAVORITES_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Favorites.
        /// </summary>
        internal static string FAVORITES_HIDE {
            get {
                return ResourceManager.GetString("FAVORITES_HIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Favorites.
        /// </summary>
        internal static string FAVORITES_SHOW {
            get {
                return ResourceManager.GetString("FAVORITES_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully fetched directory listing..
        /// </summary>
        internal static string FETCHED_LISTING {
            get {
                return ResourceManager.GetString("FETCHED_LISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching drives.
        /// </summary>
        internal static string FETCHING_DRIVES {
            get {
                return ResourceManager.GetString("FETCHING_DRIVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching directory listing of: {0}.
        /// </summary>
        internal static string FETCHING_LISTING {
            get {
                return ResourceManager.GetString("FETCHING_LISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching directory listing for path: {0} - Error: {1}.
        /// </summary>
        internal static string FETCHING_LISTING_ERROR {
            get {
                return ResourceManager.GetString("FETCHING_LISTING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching root directories.
        /// </summary>
        internal static string FETCHING_ROOT_DIRECTORIES {
            get {
                return ResourceManager.GetString("FETCHING_ROOT_DIRECTORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted file: {0}.
        /// </summary>
        internal static string FILE_DELETED {
            get {
                return ResourceManager.GetString("FILE_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file: {0}.
        /// </summary>
        internal static string FILE_DELETING {
            get {
                return ResourceManager.GetString("FILE_DELETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully downloaded file: {0}.
        /// </summary>
        internal static string FILE_DOWNLOADED {
            get {
                return ResourceManager.GetString("FILE_DOWNLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file: {0}.
        /// </summary>
        internal static string FILE_DOWNLOADING {
            get {
                return ResourceManager.GetString("FILE_DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE MANAGER.
        /// </summary>
        internal static string FILE_MANAGER {
            get {
                return ResourceManager.GetString("FILE_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Missing.
        /// </summary>
        internal static string FILE_MISSING {
            get {
                return ResourceManager.GetString("FILE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name:.
        /// </summary>
        internal static string FILE_NAME {
            get {
                return ResourceManager.GetString("FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Name.
        /// </summary>
        internal static string FILE_NAME_DUPLICATE {
            get {
                return ResourceManager.GetString("FILE_NAME_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name can&apos;t be empty..
        /// </summary>
        internal static string FILE_NAME_EMPTY {
            get {
                return ResourceManager.GetString("FILE_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with this name already exists..
        /// </summary>
        internal static string FILE_NAME_EXISTS {
            get {
                return ResourceManager.GetString("FILE_NAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a file with this name in your games..
        /// </summary>
        internal static string FILE_NAME_EXISTS_IN_GAMES {
            get {
                return ResourceManager.GetString("FILE_NAME_EXISTS_IN_GAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File.
        /// </summary>
        internal static string FILE_RENAME {
            get {
                return ResourceManager.GetString("FILE_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename file. Error: {0}.
        /// </summary>
        internal static string FILE_RENAME_ERROR {
            get {
                return ResourceManager.GetString("FILE_RENAME_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to rename this file?\n\nNote: It will not affect being able to load the game..
        /// </summary>
        internal static string FILE_RENAME_GAME {
            get {
                return ResourceManager.GetString("FILE_RENAME_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully renamed file to: {0}.
        /// </summary>
        internal static string FILE_RENAMED {
            get {
                return ResourceManager.GetString("FILE_RENAMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming file to: {0}.
        /// </summary>
        internal static string FILE_RENAMING {
            get {
                return ResourceManager.GetString("FILE_RENAMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file doesn&apos;t exist on your computer..
        /// </summary>
        internal static string FILE_UPLOAD_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_UPLOAD_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully uploaded file: {0}.
        /// </summary>
        internal static string FILE_UPLOADED {
            get {
                return ResourceManager.GetString("FILE_UPLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file to: {0}.
        /// </summary>
        internal static string FILE_UPLOADING {
            get {
                return ResourceManager.GetString("FILE_UPLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string FILES {
            get {
                return ResourceManager.GetString("FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These files weren&apos;t installed to the connected console..
        /// </summary>
        internal static string FILES_NOT_INSTALLED_TO_CONNECTED_CONSOLE {
            get {
                return ResourceManager.GetString("FILES_NOT_INSTALLED_TO_CONNECTED_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Folder.
        /// </summary>
        internal static string FOLDER_CREATE {
            get {
                return ResourceManager.GetString("FOLDER_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create new folder. Error: {0}.
        /// </summary>
        internal static string FOLDER_CREATE_ERROR {
            get {
                return ResourceManager.GetString("FOLDER_CREATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created folder: {0}.
        /// </summary>
        internal static string FOLDER_CREATED {
            get {
                return ResourceManager.GetString("FOLDER_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating folder: {0}.
        /// </summary>
        internal static string FOLDER_CREATING {
            get {
                return ResourceManager.GetString("FOLDER_CREATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted folder: {0}.
        /// </summary>
        internal static string FOLDER_DELETED {
            get {
                return ResourceManager.GetString("FOLDER_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting folder: {0}.
        /// </summary>
        internal static string FOLDER_DELETING {
            get {
                return ResourceManager.GetString("FOLDER_DELETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download folder. Error: {0}.
        /// </summary>
        internal static string FOLDER_DOWNLOAD_ERROR {
            get {
                return ResourceManager.GetString("FOLDER_DOWNLOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully downloaded folder: {0}.
        /// </summary>
        internal static string FOLDER_DOWNLOADED {
            get {
                return ResourceManager.GetString("FOLDER_DOWNLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading folder: {0}.
        /// </summary>
        internal static string FOLDER_DOWNLOADING {
            get {
                return ResourceManager.GetString("FOLDER_DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Name:.
        /// </summary>
        internal static string FOLDER_NAME {
            get {
                return ResourceManager.GetString("FOLDER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A folder with this name already exists.
        /// </summary>
        internal static string FOLDER_NAME_EXISTS {
            get {
                return ResourceManager.GetString("FOLDER_NAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Folder.
        /// </summary>
        internal static string FOLDER_RENAME {
            get {
                return ResourceManager.GetString("FOLDER_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename folder. Error: {0}.
        /// </summary>
        internal static string FOLDER_RENAME_ERROR {
            get {
                return ResourceManager.GetString("FOLDER_RENAME_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully renamed folder: {0}.
        /// </summary>
        internal static string FOLDER_RENAMED {
            get {
                return ResourceManager.GetString("FOLDER_RENAMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming folder: {0}.
        /// </summary>
        internal static string FOLDER_RENAMING {
            get {
                return ResourceManager.GetString("FOLDER_RENAMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully uploaded folder: {0}.
        /// </summary>
        internal static string FOLDER_UPLOADED {
            get {
                return ResourceManager.GetString("FOLDER_UPLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading folder to: {0}.
        /// </summary>
        internal static string FOLDER_UPLOADING {
            get {
                return ResourceManager.GetString("FOLDER_UPLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME CHEATS.
        /// </summary>
        internal static string GAME_CHEATS {
            get {
                return ResourceManager.GetString("GAME_CHEATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Launcher.
        /// </summary>
        internal static string GAME_LAUNCHER {
            get {
                return ResourceManager.GetString("GAME_LAUNCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME MODS.
        /// </summary>
        internal static string GAME_MODS {
            get {
                return ResourceManager.GetString("GAME_MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Game Regions.
        /// </summary>
        internal static string GAME_REGIONS {
            get {
                return ResourceManager.GetString("GAME_REGIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Save Resigner.
        /// </summary>
        internal static string GAME_SAVE_RESIGNER {
            get {
                return ResourceManager.GetString("GAME_SAVE_RESIGNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME SAVES.
        /// </summary>
        internal static string GAME_SAVES {
            get {
                return ResourceManager.GetString("GAME_SAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Update Finder.
        /// </summary>
        internal static string GAME_UPDATE_FINDER {
            get {
                return ResourceManager.GetString("GAME_UPDATE_FINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAMES.
        /// </summary>
        internal static string GAMES {
            get {
                return ResourceManager.GetString("GAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET STARTED.
        /// </summary>
        internal static string GET_STARTED {
            get {
                return ResourceManager.GetString("GET_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOMEBREW.
        /// </summary>
        internal static string HOMEBREW {
            get {
                return ResourceManager.GetString("HOMEBREW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How-To Guides for ModioX.
        /// </summary>
        internal static string HOWTO_GUIDE {
            get {
                return ResourceManager.GetString("HOWTO_GUIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized.
        /// </summary>
        internal static string INITIALIZED {
            get {
                return ResourceManager.GetString("INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing the application database.
        /// </summary>
        internal static string INITIALIZING_APP_DB {
            get {
                return ResourceManager.GetString("INITIALIZING_APP_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install File.
        /// </summary>
        internal static string INSTALL_FILE {
            get {
                return ResourceManager.GetString("INSTALL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Files.
        /// </summary>
        internal static string INSTALL_FILES {
            get {
                return ResourceManager.GetString("INSTALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string INSTALLED {
            get {
                return ResourceManager.GetString("INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALLED MODS.
        /// </summary>
        internal static string INSTALLED_MODS {
            get {
                return ResourceManager.GetString("INSTALLED_MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string INSTALLING {
            get {
                return ResourceManager.GetString("INSTALLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Games.
        /// </summary>
        internal static string LABEL_ADD_TO_GAMES {
            get {
                return ResourceManager.GetString("LABEL_ADD_TO_GAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string LABEL_BYTES {
            get {
                return ResourceManager.GetString("LABEL_BYTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string LABEL_CATEGORY {
            get {
                return ResourceManager.GetString("LABEL_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string LABEL_DELETE {
            get {
                return ResourceManager.GetString("LABEL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        internal static string LABEL_DIRECTORIES {
            get {
                return ResourceManager.GetString("LABEL_DIRECTORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string LABEL_DIRECTORY {
            get {
                return ResourceManager.GetString("LABEL_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string LABEL_DOWNLOAD {
            get {
                return ResourceManager.GetString("LABEL_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded On.
        /// </summary>
        internal static string LABEL_DOWNLOADED_ON {
            get {
                return ResourceManager.GetString("LABEL_DOWNLOADED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string LABEL_FILE {
            get {
                return ResourceManager.GetString("LABEL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string LABEL_FILES {
            get {
                return ResourceManager.GetString("LABEL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string LABEL_IMAGE {
            get {
                return ResourceManager.GetString("LABEL_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified On.
        /// </summary>
        internal static string LABEL_LAST_MODIFIED {
            get {
                return ResourceManager.GetString("LABEL_LAST_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Type.
        /// </summary>
        internal static string LABEL_MOD_TYPE {
            get {
                return ResourceManager.GetString("LABEL_MOD_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LABEL_NAME {
            get {
                return ResourceManager.GetString("LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string LABEL_NEW_FOLDER {
            get {
                return ResourceManager.GetString("LABEL_NEW_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Explorer.
        /// </summary>
        internal static string LABEL_OPEN_EXPLORER {
            get {
                return ResourceManager.GetString("LABEL_OPEN_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string LABEL_PLATFORM {
            get {
                return ResourceManager.GetString("LABEL_PLATFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string LABEL_REFRESH {
            get {
                return ResourceManager.GetString("LABEL_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string LABEL_REGION {
            get {
                return ResourceManager.GetString("LABEL_REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string LABEL_RENAME {
            get {
                return ResourceManager.GetString("LABEL_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string LABEL_SIZE {
            get {
                return ResourceManager.GetString("LABEL_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string LABEL_TYPE {
            get {
                return ResourceManager.GetString("LABEL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string LABEL_UPLOAD {
            get {
                return ResourceManager.GetString("LABEL_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string LABEL_VERSION {
            get {
                return ResourceManager.GetString("LABEL_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but this language is currently not supported yet. If you would like to help us add this language, please join our Discord Server and let us know!.
        /// </summary>
        internal static string LANGUAGE_HELP {
            get {
                return ResourceManager.GetString("LANGUAGE_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Not Supported.
        /// </summary>
        internal static string LANGUAGE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("LANGUAGE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        internal static string LAST_UPDATED {
            get {
                return ResourceManager.GetString("LAST_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LATEST NEWS.
        /// </summary>
        internal static string LATEST_NEWS {
            get {
                return ResourceManager.GetString("LATEST_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch File Editor.
        /// </summary>
        internal static string LAUNCH_FILE_EDITOR {
            get {
                return ResourceManager.GetString("LAUNCH_FILE_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Imported Mods.
        /// </summary>
        internal static string MANAGE_IMPORTED_MODS {
            get {
                return ResourceManager.GetString("MANAGE_IMPORTED_MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODS.
        /// </summary>
        internal static string MODS {
            get {
                return ResourceManager.GetString("MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure Neighborhood is installed on your computer.
        /// </summary>
        internal static string NEIGHBORHOOD_NOT_FOUND {
            get {
                return ResourceManager.GetString("NEIGHBORHOOD_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO ANNOUNCEMENTS.
        /// </summary>
        internal static string NO_ANNOUNCEMENTS {
            get {
                return ResourceManager.GetString("NO_ANNOUNCEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Console Connected.
        /// </summary>
        internal static string NO_CONSOLE_CONNECTED {
            get {
                return ResourceManager.GetString("NO_CONSOLE_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Console Profile.
        /// </summary>
        internal static string NO_CONSOLE_PROFILE {
            get {
                return ResourceManager.GetString("NO_CONSOLE_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO CONSOLE PROFILES.
        /// </summary>
        internal static string NO_CONSOLE_PROFILES {
            get {
                return ResourceManager.GetString("NO_CONSOLE_PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Input.
        /// </summary>
        internal static string NO_INPUT {
            get {
                return ResourceManager.GetString("NO_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be connected to the Internet to use this application..
        /// </summary>
        internal static string NO_INTERNET_CONNECTION {
            get {
                return ResourceManager.GetString("NO_INTERNET_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Detected.
        /// </summary>
        internal static string NO_INTERNET_CONNECTION_TITLE {
            get {
                return ResourceManager.GetString("NO_INTERNET_CONNECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have No Lists.
        /// </summary>
        internal static string NO_LISTS {
            get {
                return ResourceManager.GetString("NO_LISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No news is good news!.
        /// </summary>
        internal static string NO_NEWS_IS_GOOD_NEWS {
            get {
                return ResourceManager.GetString("NO_NEWS_IS_GOOD_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        internal static string NOT_CONNECTED {
            get {
                return ResourceManager.GetString("NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Installed.
        /// </summary>
        internal static string NOT_INSTALLED {
            get {
                return ResourceManager.GetString("NOT_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string OPEN_FILE {
            get {
                return ResourceManager.GetString("OPEN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        internal static string OPEN_FOLDER {
            get {
                return ResourceManager.GetString("OPEN_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONS.
        /// </summary>
        internal static string OPTIONS {
            get {
                return ResourceManager.GetString("OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package File Manager.
        /// </summary>
        internal static string PACKAGE_MANAGER {
            get {
                return ResourceManager.GetString("PACKAGE_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACKAGES.
        /// </summary>
        internal static string PACKAGES {
            get {
                return ResourceManager.GetString("PACKAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLUGINS.
        /// </summary>
        internal static string PLUGINS {
            get {
                return ResourceManager.GetString("PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to connect....
        /// </summary>
        internal static string READY_TO_CONNECT {
            get {
                return ResourceManager.GetString("READY_TO_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESOURCES.
        /// </summary>
        internal static string RESOURCES {
            get {
                return ResourceManager.GetString("RESOURCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required.
        /// </summary>
        internal static string RESTART_REQUIRED {
            get {
                return ResourceManager.GetString("RESTART_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart the application for this change to take effect. Would you like to restart now?.
        /// </summary>
        internal static string RESTART_TAKE_AFFECT {
            get {
                return ResourceManager.GetString("RESTART_TAKE_AFFECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan For Xbox Consoles.
        /// </summary>
        internal static string SCAN_XBOX_CONSOLES {
            get {
                return ResourceManager.GetString("SCAN_XBOX_CONSOLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning for Xbox consoles....
        /// </summary>
        internal static string SCANNING_XBOX_CONSOLES {
            get {
                return ResourceManager.GetString("SCANNING_XBOX_CONSOLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished scanning for Xbox consoles..
        /// </summary>
        internal static string SCANNING_XBOX_FINISHED {
            get {
                return ResourceManager.GetString("SCANNING_XBOX_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Downloads Location.
        /// </summary>
        internal static string SET_DOWNLOADS_LOCATION {
            get {
                return ResourceManager.GetString("SET_DOWNLOADS_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIAL THANKS.
        /// </summary>
        internal static string SPECIAL_THANKS {
            get {
                return ResourceManager.GetString("SPECIAL_THANKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Library.
        /// </summary>
        internal static string STARTUP_LIBRARY {
            get {
                return ResourceManager.GetString("STARTUP_LIBRARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATISTICS.
        /// </summary>
        internal static string STATISTICS {
            get {
                return ResourceManager.GetString("STATISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT MODS.
        /// </summary>
        internal static string SUBMIT_MODS {
            get {
                return ResourceManager.GetString("SUBMIT_MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected to console.
        /// </summary>
        internal static string SUCCESS_CONNECTED {
            get {
                return ResourceManager.GetString("SUCCESS_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully disconnected from console.
        /// </summary>
        internal static string SUCCESS_DISCONNECTED {
            get {
                return ResourceManager.GetString("SUCCESS_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully loaded the database - Finalizing application data....
        /// </summary>
        internal static string SUCCESS_LOADED_DB {
            get {
                return ResourceManager.GetString("SUCCESS_LOADED_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully fetched root directories.
        /// </summary>
        internal static string SUCCESS_ROOT_DIRECTORIES {
            get {
                return ResourceManager.GetString("SUCCESS_ROOT_DIRECTORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOOLS.
        /// </summary>
        internal static string TOOLS {
            get {
                return ResourceManager.GetString("TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Cheats.
        /// </summary>
        internal static string TOTAL_GAME_CHEATS {
            get {
                return ResourceManager.GetString("TOTAL_GAME_CHEATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Mods.
        /// </summary>
        internal static string TOTAL_GAME_MODS {
            get {
                return ResourceManager.GetString("TOTAL_GAME_MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Saves.
        /// </summary>
        internal static string TOTAL_GAME_SAVES {
            get {
                return ResourceManager.GetString("TOTAL_GAME_SAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homebrew.
        /// </summary>
        internal static string TOTAL_HOMEBREW {
            get {
                return ResourceManager.GetString("TOTAL_HOMEBREW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        internal static string TOTAL_PACKAGES {
            get {
                return ResourceManager.GetString("TOTAL_PACKAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string TOTAL_PLUGINS {
            get {
                return ResourceManager.GetString("TOTAL_PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string TOTAL_RESOURCES {
            get {
                return ResourceManager.GetString("TOTAL_RESOURCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to.
        /// </summary>
        internal static string UNABLE_CONNECT {
            get {
                return ResourceManager.GetString("UNABLE_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load database..
        /// </summary>
        internal static string UNABLE_LOAD_DATABASE {
            get {
                return ResourceManager.GetString("UNABLE_LOAD_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open File Explorer for directory: {0} - Error {1}.
        /// </summary>
        internal static string UNABLE_TO_OPEN_EXPLORER {
            get {
                return ResourceManager.GetString("UNABLE_TO_OPEN_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfavorite.
        /// </summary>
        internal static string UNFAVORITE {
            get {
                return ResourceManager.GetString("UNFAVORITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall All Items.
        /// </summary>
        internal static string UNINSTALL_ALL_ITEMS {
            get {
                return ResourceManager.GetString("UNINSTALL_ALL_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall File.
        /// </summary>
        internal static string UNINSTALL_FILE {
            get {
                return ResourceManager.GetString("UNINSTALL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Files.
        /// </summary>
        internal static string UNINSTALL_FILES {
            get {
                return ResourceManager.GetString("UNINSTALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Item.
        /// </summary>
        internal static string UNINSTALL_ITEMS {
            get {
                return ResourceManager.GetString("UNINSTALL_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled.
        /// </summary>
        internal static string UNINSTALLED {
            get {
                return ResourceManager.GetString("UNINSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        internal static string UNINSTALLING {
            get {
                return ResourceManager.GetString("UNINSTALLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to upload to console. Error: {0}.
        /// </summary>
        internal static string UPLOAD_ERROR {
            get {
                return ResourceManager.GetString("UPLOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        internal static string VIEW_DETAILS {
            get {
                return ResourceManager.GetString("VIEW_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature requires webMAN installed on your console..
        /// </summary>
        internal static string WEBMAN_REQUIRED {
            get {
                return ResourceManager.GetString("WEBMAN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now connected to.
        /// </summary>
        internal static string YOU_ARE_NOW_CONNECTED_TO {
            get {
                return ResourceManager.GetString("YOU_ARE_NOW_CONNECTED_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be connected to {0} to uninstall the files..
        /// </summary>
        internal static string YOU_MUST_BE_CONNECTED_TO_UNINSTALL_FILES {
            get {
                return ResourceManager.GetString("YOU_MUST_BE_CONNECTED_TO_UNINSTALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be connected to your console to use this feature..
        /// </summary>
        internal static string YOU_MUST_BE_CONNECTED_TO_USE_FEATURE {
            get {
                return ResourceManager.GetString("YOU_MUST_BE_CONNECTED_TO_USE_FEATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Lists.
        /// </summary>
        internal static string YOUR_LISTS {
            get {
                return ResourceManager.GetString("YOUR_LISTS", resourceCulture);
            }
        }
    }
}
