//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModioX.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModioX.Languages.es", typeof(es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir nuevo perfil de consola.
        /// </summary>
        internal static string Add_New_Console_Profile {
            get {
                return ResourceManager.GetString("Add New Console Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANUNCIOS.
        /// </summary>
        internal static string ANNOUNCEMENTS {
            get {
                return ResourceManager.GetString("ANNOUNCEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMBIAR REGISTRO.
        /// </summary>
        internal static string CHANGE_LOG {
            get {
                return ResourceManager.GetString("CHANGE LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haga clic en &apos;Agregar nueva consola&apos; para crear un perfil.
        /// </summary>
        internal static string Click__Add_New_Console__to_create_a_profile {
            get {
                return ResourceManager.GetString("Click \'Add New Console\' to create a profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONECTAR.
        /// </summary>
        internal static string CONNECT {
            get {
                return ResourceManager.GetString("CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectarse a la consola.
        /// </summary>
        internal static string Connect_to_console {
            get {
                return ResourceManager.GetString("Connect to console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectado a.
        /// </summary>
        internal static string Connecting_to {
            get {
                return ResourceManager.GetString("Connecting to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La conexión falló.
        /// </summary>
        internal static string Connection_Failed {
            get {
                return ResourceManager.GetString("Connection Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRIBUYENTES.
        /// </summary>
        internal static string CONTRIBUTORS {
            get {
                return ResourceManager.GetString("CONTRIBUTORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDITOS.
        /// </summary>
        internal static string CREDITS {
            get {
                return ResourceManager.GetString("CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLERO.
        /// </summary>
        internal static string DASHBOARD {
            get {
                return ResourceManager.GetString("DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Default_Game_Regions {
            get {
                return ResourceManager.GetString("Default Game Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedo encontrar el directorio.
        /// </summary>
        internal static string Directory_can_t_find {
            get {
                return ResourceManager.GetString("Directory can\'t find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este directorio no existe en su computadora.
        /// </summary>
        internal static string Directory_does_not_exist {
            get {
                return ResourceManager.GetString("Directory does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconectar.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconectar de la consola.
        /// </summary>
        internal static string Disconnect_from_console {
            get {
                return ResourceManager.GetString("Disconnect from console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconectando de la consola.
        /// </summary>
        internal static string Disconnecting_from_console {
            get {
                return ResourceManager.GetString("Disconnecting from console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargado.
        /// </summary>
        internal static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargando....
        /// </summary>
        internal static string Downloading___ {
            get {
                return ResourceManager.GetString("Downloading...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCARGAS.
        /// </summary>
        internal static string DOWNLOADS {
            get {
                return ResourceManager.GetString("DOWNLOADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación de descargas.
        /// </summary>
        internal static string Downloads_Location {
            get {
                return ResourceManager.GetString("Downloads Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar perfiles de consola.
        /// </summary>
        internal static string Edit_Console_Profiles {
            get {
                return ResourceManager.GetString("Edit Console Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorito.
        /// </summary>
        internal static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo unidades.
        /// </summary>
        internal static string Fetching_drives {
            get {
                return ResourceManager.GetString("Fetching drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo directorios raíz.
        /// </summary>
        internal static string Fetching_root_directories {
            get {
                return ResourceManager.GetString("Fetching root directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GESTOR DE ARCHIVOS.
        /// </summary>
        internal static string FILE_MANAGER {
            get {
                return ResourceManager.GetString("FILE MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODS DE JUEGO.
        /// </summary>
        internal static string GAME_MODS {
            get {
                return ResourceManager.GetString("GAME MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUEGOS GUARDADOS.
        /// </summary>
        internal static string GAME_SAVES {
            get {
                return ResourceManager.GetString("GAME SAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Saves Totales.
        /// </summary>
        internal static string Game_Saves_Total {
            get {
                return ResourceManager.GetString("Game Saves Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUEGOS.
        /// </summary>
        internal static string GAMES {
            get {
                return ResourceManager.GetString("GAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYUDA.
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocultar favoritos.
        /// </summary>
        internal static string Hide_Favorites {
            get {
                return ResourceManager.GetString("Hide Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOMEBREW.
        /// </summary>
        internal static string HOMEBREW {
            get {
                return ResourceManager.GetString("HOMEBREW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializado.
        /// </summary>
        internal static string Initialized {
            get {
                return ResourceManager.GetString("Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializar la base de datos de la aplicación....
        /// </summary>
        internal static string Initializing_the_application_database___ {
            get {
                return ResourceManager.GetString("Initializing the application database...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalar archivo.
        /// </summary>
        internal static string Install_File {
            get {
                return ResourceManager.GetString("Install File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalar archivos.
        /// </summary>
        internal static string Install_Files {
            get {
                return ResourceManager.GetString("Install Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalado.
        /// </summary>
        internal static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODS INSTALADOS.
        /// </summary>
        internal static string INSTALLED_MODS {
            get {
                return ResourceManager.GetString("INSTALLED MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalando....
        /// </summary>
        internal static string Installing___ {
            get {
                return ResourceManager.GetString("Installing...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de la introducción.
        /// </summary>
        internal static string Introduction_Details {
            get {
                return ResourceManager.GetString("Introduction Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma no admitido.
        /// </summary>
        internal static string Language_Not_Supported {
            get {
                return ResourceManager.GetString("Language Not Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, pero este idioma aún no es compatible. Si desea ayudarnos a agregar este idioma, ¡únase a nuestro Discord Server y háganoslo saber!.
        /// </summary>
        internal static string Language_not_supported__can_help {
            get {
                return ResourceManager.GetString("Language not supported, can help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última actualización.
        /// </summary>
        internal static string Last_Updated {
            get {
                return ResourceManager.GetString("Last Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÚLTIMAS NOTICIAS.
        /// </summary>
        internal static string LATEST_NEWS {
            get {
                return ResourceManager.GetString("LATEST NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAMOS A CONFIGURARLO.
        /// </summary>
        internal static string LET_S_GET_YOU_SETUP {
            get {
                return ResourceManager.GetString("LET\'S GET YOU SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asegúrese de que Neighborhood esté instalado en su computadora.
        /// </summary>
        internal static string Make_sure_Neighborhood_is_installed_on_your_computer {
            get {
                return ResourceManager.GetString("Make sure Neighborhood is installed on your computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODS.
        /// </summary>
        internal static string MODS {
            get {
                return ResourceManager.GetString("MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificaciones Totales.
        /// </summary>
        internal static string Mods_Total {
            get {
                return ResourceManager.GetString("Mods Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO HAY ANUNCIOS.
        /// </summary>
        internal static string NO_ANNOUNCEMENTS {
            get {
                return ResourceManager.GetString("NO ANNOUNCEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay consola conectada.
        /// </summary>
        internal static string No_Console_Connected {
            get {
                return ResourceManager.GetString("No Console Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIN PERFILES DE CONSOLA.
        /// </summary>
        internal static string NO_CONSOLE_PROFILES {
            get {
                return ResourceManager.GetString("NO CONSOLE PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se detectó conexión a Internet.
        /// </summary>
        internal static string No_Internet_connection_detected {
            get {
                return ResourceManager.GetString("No Internet connection detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se detectó Internet.
        /// </summary>
        internal static string No_Internet_Detected {
            get {
                return ResourceManager.GetString("No Internet Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡La ausencia de malas noticias son buenas noticias!.
        /// </summary>
        internal static string No_news_is_good_news_ {
            get {
                return ResourceManager.GetString("No news is good news!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conectado.
        /// </summary>
        internal static string Not_Connected {
            get {
                return ResourceManager.GetString("Not Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No instalado.
        /// </summary>
        internal static string Not_Installed {
            get {
                return ResourceManager.GetString("Not Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPCIONES.
        /// </summary>
        internal static string OPTIONS {
            get {
                return ResourceManager.GetString("OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAQUETES.
        /// </summary>
        internal static string PACKAGES {
            get {
                return ResourceManager.GetString("PACKAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paquetes Totales.
        /// </summary>
        internal static string Packages_Total {
            get {
                return ResourceManager.GetString("Packages Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLUGINS.
        /// </summary>
        internal static string PLUGINS {
            get {
                return ResourceManager.GetString("PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins Totales.
        /// </summary>
        internal static string Plugins_Total {
            get {
                return ResourceManager.GetString("Plugins Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listo para conectarse a la consola.
        /// </summary>
        internal static string Ready_to_connect_to_console {
            get {
                return ResourceManager.GetString("Ready to connect to console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECURSOS.
        /// </summary>
        internal static string RESOURCES {
            get {
                return ResourceManager.GetString("RESOURCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinicio requerido.
        /// </summary>
        internal static string Restart_Required {
            get {
                return ResourceManager.GetString("Restart Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escanear para consolas de Xbox.
        /// </summary>
        internal static string Scan_For_Xbox_Consoles {
            get {
                return ResourceManager.GetString("Scan For Xbox Consoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establecer ubicación de descargas.
        /// </summary>
        internal static string Set_Downloads_Location {
            get {
                return ResourceManager.GetString("Set Downloads Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AJUSTES.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar favoritos.
        /// </summary>
        internal static string Show_Favorites {
            get {
                return ResourceManager.GetString("Show Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRACIAS ESPECIALES.
        /// </summary>
        internal static string SPECIAL_THANKS {
            get {
                return ResourceManager.GetString("SPECIAL THANKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biblioteca de inicio.
        /// </summary>
        internal static string Startup_Library {
            get {
                return ResourceManager.GetString("Startup Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADÍSTICAS.
        /// </summary>
        internal static string STATISTICS {
            get {
                return ResourceManager.GetString("STATISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éxito.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectado con éxito a la consola.
        /// </summary>
        internal static string Successfully_connected_to_console {
            get {
                return ResourceManager.GetString("Successfully connected to console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconectado exitosamente de la consola.
        /// </summary>
        internal static string Successfully_disconnected_from_console {
            get {
                return ResourceManager.GetString("Successfully disconnected from console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorios raíz recuperados con éxito.
        /// </summary>
        internal static string Successfully_fetched_root_directories {
            get {
                return ResourceManager.GetString("Successfully fetched root directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargó correctamente la base de datos: finalizando los datos de la aplicación ....
        /// </summary>
        internal static string Successfully_loaded_the_database___Finalizing_application_data___ {
            get {
                return ResourceManager.GetString("Successfully loaded the database - Finalizing application data...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HERRAMIENTAS.
        /// </summary>
        internal static string TOOLS {
            get {
                return ResourceManager.GetString("TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incapaz de conectarse a.
        /// </summary>
        internal static string Unable_to_connect_to {
            get {
                return ResourceManager.GetString("Unable to connect to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Favorito.
        /// </summary>
        internal static string Unfavorite {
            get {
                return ResourceManager.GetString("Unfavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desinstalar archivo.
        /// </summary>
        internal static string Uninstall_File {
            get {
                return ResourceManager.GetString("Uninstall File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desinstalar archivos.
        /// </summary>
        internal static string Uninstall_Files {
            get {
                return ResourceManager.GetString("Uninstall Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desinstalado.
        /// </summary>
        internal static string Uninstalled {
            get {
                return ResourceManager.GetString("Uninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desinstalando....
        /// </summary>
        internal static string Uninstalling___ {
            get {
                return ResourceManager.GetString("Uninstalling...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahora estás conectado a.
        /// </summary>
        internal static string You_are_now_connected_to {
            get {
                return ResourceManager.GetString("You are now connected to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes listas.
        /// </summary>
        internal static string You_Have_No_Lists {
            get {
                return ResourceManager.GetString("You Have No Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe estar conectado a Internet para utilizar esta aplicación..
        /// </summary>
        internal static string You_must_be_connected_to_the_Internet_to_use_this_application_ {
            get {
                return ResourceManager.GetString("You must be connected to the Internet to use this application.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe estar conectado a su consola para utilizar esta función..
        /// </summary>
        internal static string You_must_be_connected_to_your_console_to_use_this_feature_ {
            get {
                return ResourceManager.GetString("You must be connected to your console to use this feature.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe reiniciar la aplicación para que este cambio surta efecto. ¿Le gustaría reiniciar ahora?.
        /// </summary>
        internal static string You_must_restart_the_application_for_this_change_to_take_effect__Would_you_like_to_restart_now_ {
            get {
                return ResourceManager.GetString("You must restart the application for this change to take effect. Would you like t" +
                        "o restart now?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus listas.
        /// </summary>
        internal static string Your_Lists {
            get {
                return ResourceManager.GetString("Your Lists", resourceCulture);
            }
        }
    }
}
